# Generated by Django 4.2.3 on 2023-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation',
            field=models.CharField(default='blank', max_length=2000),
        ),
    ]
