# Generated by Django 4.2.3 on 2023-07-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(blank=True),
        ),
    ]
