# Generated by Django 4.2.3 on 2023-07-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_chef_bio_recipe_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='profile_photo',
            field=models.ImageField(default='image', upload_to='images'),
        ),
    ]
