# Generated by Django 4.2.3 on 2023-07-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_chef_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='name',
            new_name='Username',
        ),
    ]
